server:
  port: 8098    #default port where the service will be started
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      

spring:    
  application:
    name: test-service   #current service name to be used by the eureka server
     
logging:
  level:
    com.example: DEBUG